/* postinstall: copy @fontsource woff2 files into assets/fonts and generate src/fonts.css.
 * Runs after `npm install`. Fully local/offline afterwards — no CDN needed.
 * Defensive: never fails the install (always exits 0). */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'assets', 'fonts');
const CSS_PATH = path.join(ROOT, 'src', 'fonts.css');

// fontsource package -> CSS font-family name
const FAMILIES = {
  'oswald': 'Oswald',
  'jetbrains-mono': 'JetBrains Mono',
  'pt-sans-narrow': 'PT Sans Narrow'
};

// standard unicode-range per subset (matches Google Fonts / fontsource)
const RANGES = {
  'latin': 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  'latin-ext': 'U+0100-02AF,U+0304,U+0308,U+0329,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF',
  'cyrillic': 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116',
  'cyrillic-ext': 'U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F'
};

function findPackageFilesDir(pkg) {
  const candidates = [
    path.join(ROOT, 'node_modules', '@fontsource', pkg, 'files')
  ];
  for (const c of candidates) {
    if (fs.existsSync(c)) return c;
  }
  return null;
}

try {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const faces = [];
  let copied = 0;

  for (const pkg of Object.keys(FAMILIES)) {
    const dir = findPackageFilesDir(pkg);
    if (!dir) { console.warn(`[fonts] @fontsource/${pkg} not found — skipping`); continue; }
    const family = FAMILIES[pkg];

    for (const file of fs.readdirSync(dir)) {
      if (!file.endsWith('.woff2')) continue;
      // filename pattern: <pkg>-<subset>-<weight>-<style>.woff2  e.g. oswald-cyrillic-600-normal.woff2
      const base = file.replace(/\.woff2$/, '');
      const parts = base.split('-');
      const style = parts[parts.length - 1];          // normal | italic
      const weight = parts[parts.length - 2];         // 400..700
      const subset = parts.slice(pkg.split('-').length, parts.length - 2).join('-'); // cyrillic / latin / ...
      if (style !== 'normal') continue;               // we only need upright faces
      if (!/^\d+$/.test(weight)) continue;
      const range = RANGES[subset];
      if (!range) continue;                           // skip unknown subsets (e.g. vietnamese)

      fs.copyFileSync(path.join(dir, file), path.join(OUT_DIR, file));
      copied++;
      faces.push(
        `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};` +
        `font-display:swap;src:url('../assets/fonts/${file}') format('woff2');` +
        `unicode-range:${range}}`
      );
    }
  }

  const header = '/* Auto-generated by tools/copy-fonts.js (postinstall). Do not edit by hand. */\n';
  fs.writeFileSync(CSS_PATH, header + faces.join('\n') + '\n');
  console.log(`[fonts] bundled ${copied} woff2 files -> assets/fonts, wrote src/fonts.css`);
} catch (e) {
  console.warn('[fonts] skipped local font bundling:', e && e.message);
  // leave any existing fonts.css in place; app falls back to system fonts
}
process.exit(0);
